import type { AlarmEvent } from '../utils/types'

export const alarms: AlarmEvent[] = [
  {
    id: 'alarm-3001',
    type: 'PASS_BY',
    status: 'OPEN',
    zone: '涉密核心区-A',
    deviceIds: ['dvs-01'],
    peopleCount: 3,
    confidence: 0.82,
    startAt: new Date(Date.now() - 42_000).toISOString(),
  },
  {
    id: 'alarm-5001',
    type: 'SNEAK_PHOTO_SUSPECTED',
    status: 'OPEN',
    zone: '涉密核心区-A',
    deviceIds: ['dvs-01', 'edge-01'],
    confidence: 0.76,
    startAt: new Date(Date.now() - 2 * 60_000 - 25_000).toISOString(),
  },
  {
    id: 'alarm-2001',
    type: 'FALL_SUSPECTED',
    status: 'OPEN',
    zone: '浴室-01',
    deviceIds: ['dvs-02', 'wifi-02'],
    confidence: 0.81,
    startAt: new Date(Date.now() - 4 * 60_000 - 10_000).toISOString(),
  },
  {
    id: 'alarm-3002',
    type: 'PASS_BY',
    status: 'ACKED',
    zone: '涉密核心区-A',
    deviceIds: ['dvs-01', 'wifi-01'],
    peopleCount: 1,
    confidence: 0.68,
    startAt: new Date(Date.now() - 7 * 60_000 - 40_000).toISOString(),
    note: '访客已登记，路线正常',
  },
  {
    id: 'alarm-5002',
    type: 'SNEAK_PHOTO_SUSPECTED',
    status: 'ACKED',
    zone: '涉密核心区-A',
    deviceIds: ['dvs-01'],
    confidence: 0.72,
    startAt: new Date(Date.now() - 12 * 60_000 - 15_000).toISOString(),
    note: '已提醒现场禁止拍摄',
  },
  // {
  //   id: 'alarm-3003',
  //   type: 'PASS_BY',
  //   status: 'CLOSED',
  //   zone: '浴室-01',
  //   deviceIds: ['wifi-02'],
  //   peopleCount: 2,
  //   confidence: 0.63,
  //   startAt: new Date(Date.now() - 18 * 60_000 - 50_000).toISOString(),
  //   endAt: new Date(Date.now() - 18 * 60_000).toISOString(),
  //   note: '夜间巡检路过',
  // },
  // {
  //   id: 'alarm-1001',
  //   type: 'INTRUSION',
  //   status: 'OPEN',
  //   zone: '涉密核心区-A',
  //   deviceIds: ['dvs-01', 'wifi-01'],
  //   confidence: 0.86,
  //   startAt: new Date(Date.now() - 26 * 60_000 - 20_000).toISOString(),
  // },
  // {
  //   id: 'alarm-1002',
  //   type: 'LOITERING',
  //   status: 'ACKED',
  //   zone: '涉密核心区-A',
  //   deviceIds: ['wifi-01'],
  //   confidence: 0.74,
  //   startAt: new Date(Date.now() - 36 * 60_000 - 5_000).toISOString(),
  //   note: '已通知巡检人员到场确认',
  // },
  // {
  //   id: 'alarm-5003',
  //   type: 'SNEAK_PHOTO_SUSPECTED',
  //   status: 'CLOSED',
  //   zone: '涉密核心区-A',
  //   deviceIds: ['dvs-01', 'edge-01'],
  //   confidence: 0.7,
  //   startAt: new Date(Date.now() - 44 * 60_000 - 12_000).toISOString(),
  //   endAt: new Date(Date.now() - 43 * 60_000 - 12_000).toISOString(),
  //   note: '已记录并上报保密办（演示口径）',
  // },
  // {
  //   id: 'alarm-2002',
  //   type: 'FALL_SUSPECTED',
  //   status: 'ACKED',
  //   zone: '浴室-01',
  //   deviceIds: ['dvs-02'],
  //   confidence: 0.78,
  //   startAt: new Date(Date.now() - 55 * 60_000).toISOString(),
  //   note: '已电话确认无大碍',
  // },
  // {
  //   id: 'alarm-3004',
  //   type: 'PASS_BY',
  //   status: 'CLOSED',
  //   zone: '涉密核心区-A',
  //   deviceIds: ['dvs-01'],
  //   peopleCount: 4,
  //   confidence: 0.66,
  //   startAt: new Date(Date.now() - 75 * 60_000 - 8_000).toISOString(),
  //   endAt: new Date(Date.now() - 73 * 60_000 - 40_000).toISOString(),
  //   note: '交接班人员经过',
  // },
]
